version: '2'
services:
  db:
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: m1k3y
  php-apache:
    build: ./php-apache
    ports:
      - "80"
    volumes:
      - ./app-src:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/app/logs
      - ./logs/apache:/var/log/apache2/
    links:
      - db
